---
title: "Teaching"
title-block-banner: img/DJI_0209.JPG
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        background-position-y: center;
        height: 200px;
      }
      </style>
---

# Teaching Philosophy
Restoration ecology is a field founded on our desire to understand multiple perspectives and use that understanding to solve problems in the natural world around us. In my work, I study ways to make restored wetland habitats as healthy as possible. Taking only one perspective into account would limit my ability to do my job effectively. I am not just an ornithologist or a biometeorologist or a biogeochemist. I look into how the landscape impacts the animals, how the animals shape the landscape, how water controls plant carbon sequestration, and how plant growth impacts the atmosphere around it. If I didn’t study biodiversity in combination with spatial ecology and carbon sequestration, I would miss key perspectives and understand less about the system I study and the problems I am trying to solve. In the same way our understanding of an object can be deepened when we change our view from two-dimensions to three-dimensions, each additional view from a different perspective provides greater insight and clarity of an idea or problem.

This guiding sentiment is not only true in my research – it is also true in my classroom. My main goals when students leave my classroom are that they can integrate multiple fields and points of view to understand an ecosystem and solve real world problems around them. In addition, I want each student to feel confident enough to keep asking questions about the world around them. The best way to cultivate this mindset is to create a curriculum that is flexible, practical, and founded on Universal Design. Every student that joins my classroom is different. They themselves provide a unique perspective and deserve to be well represented and supported in the learning environment. This is especially true in ecology coursework, as many classes are taken by students across departments. They may focus in urban planning, ecology, working lands management, and organismal science. By purposefully fostering different perspectives in my classes, at all levels of the ability, racial, gender, and socio-economic spectrum, we gain the observations, experiences, and wisdom that can only be obtained from the view at those vantage points. Therefore, having every student feel safe to participate and encouraging collaboration, I can prepare students to use multiple scientific and personal perspectives to address problems.   

**Goal #1**: Teach students how to integrate and value multiple fields and perspectives. Ecologists need to be able to combine information from multiple fields to form a scientific understanding of their environment. They also need to consider multiple human perspectives, as stakeholder values and interests will determine whether management solutions supported by science will be implemented in reality. I train students to consider perspectives and fields through a variety of activities in the classroom. For example, in my drone class, I may ask students to group up with students from different major programs and provide them with a hypothetical restoration project that I want them to critique. They role play as certain stakeholders and discuss whether they can reach a compromise that achieves the restoration goals and supports the local community. 

I work to ensure students feel confident sharing in class by making sure that all components of the course feel tailored to them through Universal Design. I provide lecture notes before class in addition to presenting the information verbally in class so that auditory and visual learners are both accommodated. Our in class assignments are hands on and practical to ensure tactile learners feel supported as well. I prioritize active learning, especially with collaborative student teaching. This manifests as breaks in lectures for think-pair-share question activities or having students pick from a list of readings and summarize their papers for students who picked other papers. I provide creative freedom in open ended discussion assignments and presentations, allowing students to respond in ways that represent their interests and values. The combination of these tactics creates a classroom culture where students feel seen, cared for, and free to participate, even if they are unsure of their answers or approaches. This feeling encourages students to be confident and share their perspectives. 

**Goal #2**: Prepare students to solve real world problems. In ecology, rarely does our actual work rely on facts memorized for tests. Instead, we need to be able to take information we have access to and use that to solve complex, practical problems. Our skills are our greatest assets. For this reason, I choose to keep traditional tests to a minimum in the classroom. I prefer my assessments of student learning to be focused on applying skills that have been taught previously to solve novel problems. If students can use their skills, critically think about a new problem, and form conclusions about the issue with multiple perspectives, I consider the student to be succeeding in the course. 

When I was teaching Ecological Analysis, our final lab assessment was devoted to creating a suitability analysis on fire risk in the Bay Area. Suitability analyses are a key assessment type in ecology and urban planning that allow us to use multiple data sets and perspectives to decide on areas are best (or least) suited for certain land use. In this case, we wanted students to identify which areas in the Bay are most threatened by fires in the future. The assignment asked students to use skills from past ArcGIS labs including calculating slope from DEMs and creating buffers around roads to represent distance from emergency services. In addition, they used maps of “extreme fire risk” in the area and federal lands provided to them. In this practical component of the assignment, students succeeded if they could identify the singular worst federal land threatened by fire. 

However, using the tools was not the only objective. I wanted them to critically engage with the workflow. To do this, we asked students to explain whether they believed our analysis to be sufficient or if more data would be helpful. Each student provided different additional data that they would recommend including in the future such as the flammability of each structure (suggested by urban planning students) or vegetation health and wind direction (suggested by environmental science students). In lab, students got to collaborate on this component and share their perspective on what a satisfactory analysis would look like. Overall, this final assessment of student learning tested for their ability to apply practical skills to solve a real problem: identifying structures to protect in the upcoming fire season. 

**Goal #3**: Prepare students to keep asking questions. Science can’t happen if we aren’t comfortable asking questions. Our work always aims to answer a question, so encouraging students to be as confident in what they don’t know as what they do know is a top priority in my classroom. I aim to address this through my classroom culture. When I teach Ecological Analysis, I announce to the students frequently that my job is to answer their questions, so they are never a burden for asking. While students work independently, I wander the classroom ready to walk students through a workflow or answer clarifying questions. This reinforces that my priority during the class time is helping them. 

Getting students to feel comfortable asking technical questions is a good first start, but I also want to teach the students how to answer their own questions themselves through problem solving. When a student asks me for help in ArcGIS, I always ask them first what the step they are on is trying to achieve. I ask what they think is going wrong, so they can learn how to identify the issue in their work. Then, I ask what they think the next step would be to fix it. When a student is truly lost and doesn’t know the next step, we work on it together, and I can guide them. However, I can see over the semester that students eventually answer their own questions once they are comfortable with this line of investigating their work and understanding.  

Finally, I want students to be prepared to answer the questions that other students have. As I work with one student, I will encourage other students to work together to troubleshoot their own issues. Not only does this allow students to reinforce their own learning by teaching another student, but it also provides them an opportunity to form relationships with other students in lab. They share their approaches and perspective on open ended discussion questions, which also helps us achieve Goal #1. 

Every semester, I remain dedicated to keeping my strategies tailored to each student and committing the extra time that students need to master a concept. I believe diversity and inclusion at all levels of the ability, racial, gender, and socio-economic spectrum is critical for academic and research success, especially in ecology. At UC Berkeley, I work with students and faculty not in spite of, but rather, in celebration of the perspective that their unique identity and experience adds to the pursuit of knowledge. I teach students to embrace multiple perspectives as ecologists, to be confident when asking questions, and to use skills learned in my classroom to solve real world problems. 

# Teaching CV

## Guest Lecturer - University of California, Berkeley, CA   		
### Drones and Remote Sensing – Applied Remote Sensing (Spring 2025)  
### Field Safety for Graduate Students - Research Approaches in Environmental Science, Policy, and Management (Spring 2025)  


## Graduate Student Instructor - University of California, Berkeley
### *August - December 2023, 2024* 
### Course: Ecological Analysis 

As a Graduate Student Instructor, I have taught lab sections of Ecological Analysis, an upper level undergraduate course in the Department of Environmental Science, Policy, and Management. In the lab sections, I provided training in the use of ArcGIS and Excel to solve landscape ecology and urban planning problems. The instruction was supplemented by individualized troubleshooting in class and office hours. Each semester, I was responsible for teaching and grading the work of 50 students. 

## Long-term Substitute Teacher - LiFT Academy, Seminole, FL
### *February 2023 - May 2023*
### Short-Term Assignments: Kindergarten - 5th grade, Algebra
### Long-Term Assignments: High School Religion, Pre-Algebra, High School English 1-4, Life Skills

LiFT Academy is a school specializing in providing high quality, accessible, and inclusive education to students with neurological and physical diversities. Their students range from having Cerebral Palsy to being non-verbal. As a long-term substitute across a variety of high school subjects, I was responsible for creating curriculum for the class as a whole and then adapting the work to fit the needs and accommodations of each of my students. My class sizes ranged from eight to 30 students. I also acted as a tutor for individual students on life skills such as telling time, hand writing, and counting money. When I was not teaching in my long-term assignments, I filled teaching assistant positions in the elementary school. In addition, I created activities and crafts for students to do during my two to three aftercare shifts each week. 

## Student-Athlete Tutor - Duke University Athletics Department
### *September 2018 - May 2020*

As a Student-Athlete Tutor, I provided flexible tutoring for athletes who had missed classes or study time due to their training and competition schedules. Most sessions, I would teach my students the content of the lecture and provide practice questions to check for understanding as we went. In addition, I would provide feedback on writing and lab reports for each student. Our sessions were also focused on creating sustainable study habits and giving my students skills to help them better adjust to life as a college student-athlete. 

## Study Buddies - Founder and Past President - Seminole, FL
### *May 2014 - June 2016*

My first time working at LiFT Academy occurred in high school, when I created the organization Study Buddies to connect students from my high school with LiFT students to provide free tutoring sessions. Our organization brought 30 tutors to campus twice a week and offered tutoring in all subjects for students from kindergarten to high school. I personally tutored students in elementary English, elementary and high school math, economics, religion, and history. 

# Mentoring Experience 
## Sponsored Projects for Undergraduate Research (SPUR) Mentor - UC Berkeley, CA
## *February 2024 – Present*

As a SPUR mentor, I have created positions within my research for undergraduate students to gain valuable skills and research experience early in their career for college credit. My first SPUR student worked with me to complete a literature review on the study of biodiversity and biogeochemical cycling in wetlands. I taught her the process behind a literature review, and we met weekly to discuss our findings. We are currently drafting a manuscript from this project for publication which will be my student’s first publication. 

In addition, I have been joined by five students in the field through SPUR. In my local restored wetland sites, my students conduct point counts for birds at sunrise, assist in my drone flights over the landscape, and set audio recording equipment. They each have the opportunity to learn applicable field skills and get experience flying drones, which will open further field opportunities to them if they are interested. I am mentoring one of these students on her senior thesis as she investigates carbon and algae in our wetlands. 

## College of Natural Resources Mentoring - Mentor - UC Berkeley, CA 	      
## *September 2023 – May 2024*

I mentored two environmental science majors who recently finished their freshman year. We met biweekly to work on areas they were interested in improving: time management, writing styles, and creating college level work. In addition, I gathered advice and resources from my colleagues in legal careers and law schools that my students were interested in pursuing. 

## Females and Allies Excelling More in Math, Engineering, and Science (FEMMES) Connect Mentor - Duke University, NC		     	 
## *January 2017 - January 2018*

As a FEMMES Mentor, I worked with my mentee, an eighth grade girl, to show her potential career pathways that are open to her in science. She expressed an interest in research but was unsure what those jobs actually looked like. I brought her for a tour of the genetics lab and greenhouse I was working in, built robots with her, and helped her meet other female science students in other fields like medicine and chemistry. 

